### ISSUE TITLE
Crash on 1.20.1 Quilt

### ISSUE THREAD

**Issue by acikek** [jaskarth/ecotones#36]
Crash report: [crash-2023-06-28_18.54.49-client.txt](https://github.com/jaskarth/ecotones/files/11911970/crash-2023-06-28_18.54.49-client.txt)

**Comment by jaskarth** [comment]
Fixed, thanks!

**Comment by V-lpen** [comment]
Still getting a Quilt crash 
https://mcpaste.io/472673f1d0053b49
I am unsure if its related
